# Generated by Django 5.2.7 on 2025-10-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("eth_spot_price", models.FloatField()),
                ("btc_spot_price", models.FloatField()),
                ("spot_intrinsic_move", models.FloatField()),
                ("eth_futures_price", models.FloatField()),
                ("btc_futures_price", models.FloatField()),
                ("futures_intrinsic_move", models.FloatField()),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data_points_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название алерта")),
                ("symbol", models.CharField(max_length=20, verbose_name="Символ")),
                (
                    "condition",
                    models.CharField(
                        choices=[("above", "Выше"), ("below", "Ниже")], max_length=20, verbose_name="Условие"
                    ),
                ),
                ("target_price", models.FloatField(verbose_name="Целевая цена")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активен"), ("triggered", "Сработал"), ("cancelled", "Отменен")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_price_when_triggered",
                    models.FloatField(blank=True, null=True, verbose_name="Цена при срабатывании"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(choices=[("ETHUSDT", "ETHUSDT"), ("BTCUSDT", "BTCUSDT")], max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[("spot", "Spot"), ("linear", "Futures Linear"), ("inverse", "Futures Inverse")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.FloatField()),
            ],
            options={
                "db_table": "price_history",
                "ordering": ["symbol", "category", "timestamp"],
            },
        ),
    ]
