# Generated by Django 5.2.7 on 2025-10-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data_points_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(choices=[("ETHUSDT", "ETHUSDT"), ("BTCUSDT", "BTCUSDT")], max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[("spot", "Spot"), ("linear", "Futures Linear"), ("inverse", "Futures Inverse")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.FloatField()),
            ],
            options={
                "db_table": "price_history",
                "ordering": ["symbol", "category", "timestamp"],
                "indexes": [
                    models.Index(fields=["symbol", "category", "timestamp"], name="price_histo_symbol_04bd68_idx")
                ],
            },
        ),
    ]
