# Generated by Django 5.2.7 on 2025-10-22 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("eth_spot_price", models.FloatField()),
                ("btc_spot_price", models.FloatField()),
                ("spot_intrinsic_move", models.FloatField()),
                ("eth_futures_price", models.FloatField()),
                ("btc_futures_price", models.FloatField()),
                ("futures_intrinsic_move", models.FloatField()),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data_points_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название алерта")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("price", "Цена"),
                            ("intrinsic", "Собственное движение"),
                            ("basis", "Базис"),
                            ("volume", "Объем"),
                        ],
                        max_length=20,
                        verbose_name="Тип алерта",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, verbose_name="Символ")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("above", "Выше"),
                            ("below", "Ниже"),
                            ("cross_above", "Пересекает сверху"),
                            ("cross_below", "Пересекает снизу"),
                        ],
                        max_length=20,
                        verbose_name="Условие",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Значение")),
                ("timeframe", models.CharField(default="1h", max_length=10, verbose_name="Таймфрейм")),
                ("data_type", models.CharField(default="spot", max_length=10, verbose_name="Тип данных")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активен"), ("triggered", "Сработал"), ("cancelled", "Отменен")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Алерт",
                "verbose_name_plural": "Алерты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(choices=[("ETHUSDT", "ETHUSDT"), ("BTCUSDT", "BTCUSDT")], max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[("spot", "Spot"), ("linear", "Futures Linear"), ("inverse", "Futures Inverse")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.FloatField()),
            ],
            options={
                "db_table": "price_history",
                "ordering": ["symbol", "category", "timestamp"],
                "indexes": [
                    models.Index(fields=["symbol", "category", "timestamp"], name="price_histo_symbol_04bd68_idx")
                ],
            },
        ),
    ]
