# Generated by Django 5.2.7 on 2025-10-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("eth_spot_price", models.FloatField()),
                ("btc_spot_price", models.FloatField()),
                ("spot_intrinsic_move", models.FloatField()),
                ("eth_futures_price", models.FloatField()),
                ("btc_futures_price", models.FloatField()),
                ("futures_intrinsic_move", models.FloatField()),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("price_change", "Изменение цены"),
                            ("intrinsic_move", "Собственное движение"),
                            ("basis_change", "Изменение базиса"),
                        ],
                        max_length=20,
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("value", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
